on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run protoc
      run: |
        wget -c -O /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip \
        && unzip /tmp/protoc.zip -d /tmp/ \
        && go get -u -v google.golang.org/protobuf/cmd/protoc-gen-go \
        && /tmp/bin/protoc -I ./scheduler --go_out=./scheduler scheduler.proto
    - name: Test
      env:
        GOPRIVATE: github.com/jimen0
      run: go test -race -v ./...
